library(quantmod) 
rm()

# Symbols
symbols <- c("AAPL", "BAC"  , "CMCSA", "CVX"  , "C"     , "DIS"  , "GE"  , "HD"   , "IBM"  , "JNJ"   , "JPM"  , "KO"   , "MCD" , "MRK"    , "MSFT",
             "ORCL", "PEP"  , "PFE"  , "PG"   , "QCOM"  , "SLB"  , "VZ"  , "WFC"  , "XOM"  , "^AEX"  , "^ATX" , "^AXJO", "^BFX", "^BFX"   , "^DJA", 
             "^DJI", "^FTAS", "^FTMC", "^FTSE", "^GDAXI", "^GSPC", "^HSI", "^IBEX", "^IXIC", "^MDAXI", "^N100", "^N225", "^NDX", "^OMXIPI", "^RUT", "^SMSI")
# Load symbols into data_env
getSymbols(Symbols = symbols,  from = "2010-01-01", srs = "yahoo")

write.zoo(AAPL$AAPL.Close, file = "AAPL.csv", sep = ",")
write.zoo(BAC$BAC.Close, file = "BAC.csv", sep = ",")
write.zoo(CMCSA$CMCSA.Close, file = "CMCSA.csv", sep = ",")
write.zoo(CVX$CVX.Close, file = "CVX.csv", sep = ",")
write.zoo(C$C.Close, file = "C.csv", sep = ",")
write.zoo(DIS$DIS.Close, file = "DIS.csv", sep = ",")
write.zoo(GE$GE.Close, file = "GE.csv", sep = ",")
write.zoo(HD$HD.Close, file = "HD.csv", sep = ",")
write.zoo(IBM$IBM.Close, file = "IBM.csv", sep = ",")
write.zoo(JNJ$JNJ.Close, file = "JNJ.csv", sep = ",")
write.zoo(JPM$JPM.Close, file = "JPM.csv", sep = ",")
write.zoo(KO$KO.Close, file = "KO.csv", sep = ",")
write.zoo(MCD$MCD.Close, file = "MCD.csv", sep = ",")
write.zoo(MRK$MRK.Close, file = "MRK.csv", sep = ",")
write.zoo(MSFT$MSFT.Close, file = "MSFT.csv", sep = ",")
write.zoo(ORCL$ORCL.Close, file = "ORCL.csv", sep = ",")
write.zoo(PEP$PEP.Close, file = "PEP.csv", sep = ",")
write.zoo(PFE$PFE.Close, file = "PFE.csv", sep = ",")
write.zoo(PG$PG.Close, file = "PG.csv", sep = ",")
write.zoo(QCOM$QCOM.Close, file = "QCOM.csv", sep = ",")
write.zoo(SLB$SLB.Close, file = "SLB.csv", sep = ",")
write.zoo(VZ$VZ.Close, file = "VZ.csv", sep = ",")
write.zoo(WFC$WFC.Close, file = "WFC.csv", sep = ",")
write.zoo(XOM$XOM.Close, file = "XOM.csv", sep = ",")
#^
write.zoo(AEX$AEX.Close, file = "^AEX.csv", sep = ",")
write.zoo(ATX$ATX.Close, file = "^ATX.csv", sep = ",")
write.zoo(AXJO$AXJO.Close, file = "^AXJO.csv", sep = ",")
write.zoo(BFX$BFX.Close, file = "^BFX.csv", sep = ",")
write.zoo(DJA$DJA.Close, file = "^DJA.csv", sep = ",")
write.zoo(DJI$DJI.Close, file = "^DJI.csv", sep = ",")
write.zoo(FTAS$FTAS.Close, file = "^FTAS.csv", sep = ",")
write.zoo(FTMC$FTMC.Close, file = "^FTMC.csv", sep = ",")
write.zoo(FTSE$FTSE.Close, file = "^FTSE.csv", sep = ",")
write.zoo(GDAXI$GDAXI.Close, file = "^GDAXI.csv", sep = ",")
write.zoo(GSPC$GSPC.Close, file = "^GSPC.csv", sep = ",")
write.zoo(HSI$HSI.Close, file = "^HSI.csv", sep = ",")
write.zoo(IBEX$IBEX.Close, file = "^IBEX.csv", sep = ",")
write.zoo(IXIC$IXIC.Close, file = "^IXIC.csv", sep = ",")
write.zoo(MDAXI$MDAXI.Close, file = "^MDAXI.csv", sep = ",")
write.zoo(N100$N100.Close, file = "^N100.csv", sep = ",")
write.zoo(N225$N225.Close, file = "^N225.csv", sep = ",")
write.zoo(NDX$NDX.Close, file = "^NDX.csv", sep = ",")
write.zoo(RUT$RUT.Close, file = "^RUT.csv", sep = ",")
write.zoo(SMSI$SMSI.Close, file = "^SMSI.csv", sep = ",")

